const memberInfo = [
  {
    sectionId: 'devon',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Devon_Marantz.jpg`,
    fullName: 'Devon Marantz',
    role: 'Product Owner',
    aura: 'Imaginative',
    link: 'mailto: DMarantz@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Emily_Yang.png`,
    fullName: 'Emily Yang',
    role: 'Software Engineer',
    aura: 'Inspired',
    link: 'mailto: EYang@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Scott_Roberts.png`,
    fullName: 'Scott Roberts',
    role: 'Software Engineer',
    aura: 'Peaceful',
    link: 'mailto: SRoberts@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Kevin_Amarbayar.jpg`,
    fullName: 'Kevin Amarbyar',
    role: 'Software Engineer',
    aura: 'Lively',
    link: 'mailto: KAmarbayar@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Ervin_Mitra.jpg`,
    fullName: 'Ervin Mitra',
    role: 'Software Engineer',
    aura: 'Hipster',
    link: 'mailto: EMitra@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Jon_Azali.jpg`,
    fullName: 'Jonathan Azali',
    role: 'Software Engineer',
    aura: 'Silly',
    link: 'mailto: JAzali@talentpath.com',
  },
  {
    sectionId: 'none',
    src: `${process.env.PUBLIC_URL}/assets/img/team/Brock_Jameson.png`,
    fullName: 'Brock Jameson',
    role: 'Software Engineer',
    aura: 'Groovy',
    link: 'mailto: BJameson@talentpath.com',
  },
];

export default memberInfo;
