import React from 'react';
import PropTypes from 'prop-types';

import '../css/SearchForm.css';
import '../css/main.css';

class SearchForm extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      searchForm: {
        auraValue: 'cheerful',
      },
    };
  }

  handleSearchSubmit = event => {
    event.preventDefault();
    this.props.onSearchSubmit(this.state.searchForm);
  };

  handleChange = event => {
    this.setState({ searchForm: { auraValue: event.target.value } });
  };

  render() {
    return (
      <article>
        <section className="search-form">

          <form
            action=""
            method="GET"
            name="search"
            role="search"
            onSubmit={this.handleSearchSubmit}
          >

            <span className="grid-80">I want to be</span>

            <p className="cat-wrap">
              <select
                value={this.state.searchForm.auraValue}
                name="search categories"
                className="grid-80"
                onChange={this.handleChange}
              >
                <option value="cheerful">Cheerful</option>
                <option value="inspired">Inspired</option>
                <option value="romantic">Romantic</option>
                <option value="peaceful">Peaceful</option>
                <option value="classy">Classy</option>
                <option value="hipster">Hipster</option>
                <option value="trendy">Trendy</option>
                <option value="spiritual">Spiritual</option>
                <option value="silly">Silly</option>
                <option value="touristy">Touristy</option>
              </select>
            </p>

            <span className="grid-40">while</span>

            <p className="cat-wrap">
              <select name="search categories" className="grid-80">
                <option value="eating">Eating</option>
                <option value="studying">Studying</option>
                <option value="dating">Dating</option>
                <option value="relaxing">Relaxing</option>
                <option value="drinking">Drinking</option>
                <option value="shopping">Shopping</option>
              </select>
            </p>

            <span className="grid-40">with</span>

            <p className="cat-wrap">
              <select name="search categories" className="grid-80">
                <option value="I">Myself</option>
                <option value="friends">Friends</option>
                <option value="date">A Date</option>
              </select>
            </p>
            <p className="submit-wrap" id="submitButtonContainer">
              <button id="submitButton" className="grid-100 btn">
                {/* import magnifying glass icon later */
                /* <span class="search-icon-container">
                <?xml version="1.0" encoding="utf-8"?>
                <!-- Generated by IcoMoon.io -->
                <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"></span>
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                  id="search-icon"
                  width="768"
                  height="768"
                  viewBox="0 0 768 768"
                >
                  <g id="icomoon-ignore"></g>
                  <path
                    d="M304.5 448.5c79.5 0 144-64.5 144-144s-64.5-144-144-144-144 64.5-144 144 64.5 144 144 144zM496.5 448.5l159 159-48 48-159-159v-25.5l-9-9c-36 31.5-84 49.5-135 49.5-115.5 0-208.5-91.5-208.5-207s93-208.5 208.5-208.5 207 93 207 208.5c0 51-18 99-49.5 135l9 9h25.5z"
                  ></path>
                </svg>
              </span> */}
                Search
              </button>
            </p>
          </form>
        </section>
      </article>
    );
  }
}

SearchForm.propTypes = {
  onSearchSubmit: PropTypes.func.isRequired,
};

export default SearchForm;
